name: ares-emulator
base: core24
version: '147'
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
summary: Multi-system console emulation suite
description: |
 ares is a cross-platform, open source, multi-system emulator, focusing on accuracy and preservation.
grade: stable
confinement: strict
icon: ares.svg

apps:
  ares-emulator:
    command-chain: [snap/command-chain/override-xdg-paths]
    command: usr/bin/ares
    desktop: usr/share/applications/ares.desktop
    common-id: dev.ares.ares
    extensions: [gnome]
    plugs:
      - unity7
      - screen-inhibit-control
      - audio-playback
      - network
      - network-bind
      - network-status
      - home
      - removable-media
      - mount-observe
      - joystick
      - bluez
      - hardware-observe

plugs:
  shared-memory:
    private: true

parts:
  ares-emulator-app:
    after: [sdl3]
    plugin: cmake
    source: https://github.com/ares-emulator/ares.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    build-packages:
      - clang
      - patchelf
    cmake-parameters:
      - -Wno-dev
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DARES_BUILD_LOCAL=OFF
      - -DARES_BUNDLE_SHADERS=OFF
      - -DARES_SKIP_DEPS=ON
      - -DCMAKE_C_COMPILER=clang
      - -DCMAKE_CXX_COMPILER=clang++
      - -DARES_BUILD_OFFICIAL=YES
      - -GNinja
    override-build: |
      craftctl default
      sed -i 's|Name=ares|Name=ares [Kyu]|' $CRAFT_PART_INSTALL/usr/share/applications/ares.desktop
      patchelf --replace-needed /build/ares-emulator/stage/usr/lib/x86_64-linux-gnu/librashader.so librashader.so $CRAFT_PART_INSTALL/usr/bin/ares
      patchelf --replace-needed /root/stage/usr/lib/x86_64-linux-gnu/librashader.so librashader.so $CRAFT_PART_INSTALL/usr/bin/ares

  sdl3:
    after: [slang-shaders]
    plugin: cmake
    source: https://github.com/libsdl-org/SDL.git
    source-tag: release-3.4.2
    build-packages:
      - libdrm-dev
      - libxkbcommon-dev
      - libxss-dev
      - libfribidi-dev
      - libxcursor-dev
      - libxi-dev
      - libxrandr-dev
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo

  slang-shaders:
    after: [librashader]
    plugin: make
    source: https://github.com/libretro/slang-shaders.git
    make-parameters:
      - PREFIX=/usr

  librashader:
    plugin: nil
    source: https://github.com/SnowflakePowered/librashader.git
    source-tag: librashader-v0.10.1
    build-snaps: [rustup]
    override-build: |
      rustup default stable
      cargo run -p librashader-build-script -- --profile optimized --stable
      mkdir -p $CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/
      mkdir -p $CRAFT_PART_INSTALL/usr/include
      mv target/optimized/librashader.so $CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/librashader.so
      mv include $CRAFT_PART_INSTALL/usr/include/librashader

  command-chain:
    after: [ares-emulator-app]
    plugin: dump
    source: ./command-chain/
    organize:
      override-xdg-paths: snap/command-chain/override-xdg-paths
